// backend means the logic part of the application that handles data processing, storage, and retrieval. It is responsible for managing the core functionalities of the application, such as user authentication, database interactions, and business logic implementation. The backend communicates with the frontend (the user interface) to provide a seamless experience for users by sending and receiving data as needed.

// firebase is not a backend itself, but rather a Backend-as-a-Service (BaaS) platform provided by Google. It offers a suite of cloud-based services that developers can use to build and manage their applications without having to set up and maintain their own backend infrastructure. Firebase provides various features such as real-time databases, authentication, cloud storage, hosting, and serverless functions, making it easier for developers to implement backend functionalities quickly and efficiently.
// In summary, the backend is the underlying system that powers an application, while Firebase is a platform that provides ready-to-use backend services to simplify the development process.
//  business logic refers to the set of rules, calculations, and processes that define how a business operates and how its data is managed within an application. It encompasses the core functionalities that are specific to the business domain, such as workflows, decision-making processes, and data transformations. Business logic is implemented in the backend of an application and is responsible for ensuring that the application behaves according to the business requirements and objectives. It acts as a bridge between the user interface (frontend) and the data storage (database), processing user inputs and generating appropriate outputs based on the defined rules and conditions.


// r-r-pattern stands for "Repository-Resource Pattern." It is a design pattern used in software development to separate the data access logic from the business logic of an application. In this pattern, a "Repository" acts as an intermediary between the business logic and the data source (such as a database), providing a clean and consistent interface for data operations. The "Resource" represents the actual data entities or models that the application works with. By using the r-r-pattern, developers can achieve better organization, maintainability, and testability of their code, as it allows for easier management of data access and manipulation while keeping the business logic focused on the application's core functionalities.

//  one-tier application architecture simply means that all components of the application, including the user interface, business logic, and data storage, are contained within a single layer or tier. for example, a desktop application that runs on a user's computer and manages its own data without relying on external servers or services like calculator, excel etc.

// In contrast, multi-tier application architecture separates these components into different layers or tiers, each responsible for specific functions. For example, a three-tier architecture typically consists of a presentation tier (frontend), a logic tier (backend), and a data tier (database). This separation allows for better scalability, maintainability, and flexibility in application development and deployment.

// every browser has its own engine to interpret and run the code written in web languages like HTML, CSS, and JavaScript. These engines are responsible for rendering web pages and executing scripts to provide interactive features. Some of the most common browser engines include:
// 1. Blink: Used by Google Chrome, Microsoft Edge, Opera, and other Chromium-based browsers.
// 2. Gecko: Used by Mozilla Firefox.
// 3. WebKit: Used by Apple Safari.
// 4. Trident: Used by older versions of Microsoft Internet Explorer.
// 5. v8: JavaScript engine used by Google Chrome and Node.js.
// 6.chakra: Used by older versions of Microsoft Edge (EdgeHTML).

// js engine has call stack and heap memory. Call stack is where the function calls are stacked and executed in a LIFO (Last In, First Out) order. Heap memory is where objects and variables are stored in an unordered manner. The JS engine uses these two components to manage the execution of JavaScript code efficiently.

// js is single-threaded, meaning it can only execute one task at a time. However, it can handle asynchronous operations using mechanisms like callbacks, promises, and async/await. This allows JavaScript to perform non-blocking operations, such as making network requests or reading files, without freezing the main thread.

// event loop is a mechanism in JavaScript that allows it to handle asynchronous operations. It continuously checks the call stack and the task queue. When the call stack is empty, it takes the first task from the task queue and pushes it onto the call stack for execution. This way, JavaScript can perform non-blocking operations while still being single-threaded.

// js when running in browser environment is v8 and web apis. V8 is the JavaScript engine that interprets and executes JavaScript code, while Web APIs are provided by the browser to handle tasks like DOM manipulation, event handling, and making network requests. Together, they enable JavaScript to create dynamic and interactive web applications.

// node.js is a runtime environment that allows JavaScript to be executed on the server side, outside of a web browser. It is built on the V8 JavaScript engine used in Google Chrome and provides a platform for building scalable and high-performance applications. Node.js is commonly used for developing web servers, APIs, real-time applications, and command-line tools. It has a rich ecosystem of libraries and frameworks available through npm (Node Package Manager), making it a popular choice for backend development.

// npm stands for Node Package Manager. It is a package manager for JavaScript programming language and is the default package manager for the Node.js runtime environment. npm allows developers to easily install, share, and manage libraries and dependencies for their projects. It provides a vast repository of open-source packages that can be used to add functionality to applications, making it easier to build and maintain software.

// js cant talk with os directly because it is designed to run in a sandboxed environment, such as a web browser or Node.js, which restricts direct access to the underlying operating system for security reasons. This prevents malicious code from harming the user's system or accessing sensitive information. Instead, JavaScript interacts with the OS through APIs provided by the environment it runs in, such as Web APIs in browsers or built-in modules in Node.js, which act as intermediaries to safely perform operations like file handling, network requests, and process management.
// native bindings are interfaces that allow a programming language, such as JavaScript, to interact with native code written in languages like C or C++. These bindings enable the language to access low-level system functionalities and libraries that are not directly available within its own environment. In the context of Node.js, native bindings are used to create modules that can perform tasks like file system operations, network communication, and other performance-intensive operations by leveraging the efficiency of native code while still being accessible through JavaScript.

// lib uv is heart of node js. It is a multi-platform support library that focuses on asynchronous I/O. It provides the event loop and handles operations such as file system access, networking, and timers in a non-blocking manner. Libuv allows Node.js to perform high-performance I/O operations by offloading them to a thread pool, enabling the single-threaded JavaScript code to remain responsive while waiting for these operations to complete.

// dns-domain namung system
// DNS (Domain Name System) is a hierarchical and decentralized naming system used to translate human-readable domain names (like www.example.com) into machine-readable IP addresses.
// there are 3 types of modules in node js
// 1. Core Modules: These are built-in modules that come with Node.js and provide essential functionalities, such as 'fs' for file system operations, 'http' for creating web servers, and 'path' for handling file paths.
// 2. Local Modules: These are custom modules created by developers for specific applications. They are stored in separate files and can be imported into other files using the 'require' function.
// 3. Third-Party Modules: These are modules created by the community and shared via package managers like npm (Node Package Manager). Developers can install these modules to add additional functionalities to their applications, such as 'express' for web frameworks or 'lodash' for utility functions.

// cjs stands for CommonJS, which is a module system used in JavaScript, primarily in Node.js. It allows developers to organize their code into reusable modules by using the `require` function to import modules and the `module.exports` object to export them. CommonJS modules are synchronous, meaning that when a module is required, the code execution waits until the module is fully loaded before proceeding. This module system is widely used in server-side JavaScript development and has influenced other module systems like AMD (Asynchronous Module Definition) and ES6 modules.

// esm stands for ECMAScript Modules, which is a standardized module system introduced in ECMAScript 2015 (ES6) for JavaScript. ESM allows developers to organize their code into reusable modules using the `import` and `export` keywords. Unlike CommonJS (CJS), which is synchronous, ESM supports asynchronous loading of modules, making it more suitable for modern web development. ESM is natively supported in modern browsers and Node.js, allowing for better interoperability and code sharing between different environments. It promotes a more modular and maintainable code structure in JavaScript applications.